### ISSUE TITLE
Plugin does not start

### ISSUE THREAD

**Issue by kodan2k** [xbmc-korean-tv/addons#18]
As of today the plugin does not start anymore:

20:58:51.071 T:5288   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ondemandkorea/
20:58:51.071 T:5288   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ondemandkorea/) failed
20:58:59.592 T:2480  NOTICE: [xbmcswift2] Request for "/" matches rule for function "main_menu"
20:58:59.595 T:2480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'offscreen' is an invalid keyword argument for this function
                                            Traceback (most recent call last):
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.ondemandkorea\addon.py", line 93, in <module>
                                                plugin.run()
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 342, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 325, in _dispatch
                                                listitems = self.finish(listitems)
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\xbmcmixin.py", line 491, in finish
                                                self.add_items(items)
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\xbmcmixin.py", line 407, in add_items
                                                _items = [self._listitemify(item) for item in items]
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\xbmcmixin.py", line 312, in _listitemify
                                                item = ListItem.from_dict(**item)
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\listitem.py", line 204, in from_dict
                                                listitem = cls(label, label2, icon, thumbnail, path, fanart, offscreen)
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\listitem.py", line 34, in __init__
                                                self._listitem = xbmcgui.ListItem(**kwargs)
                                            TypeError: 'offscreen' is an invalid keyword argument for this function
                                            -->End of Python script error report<--

[kodi.log](https://github.com/xbmc-korean-tv/addons/files/5668359/kodi.log)

**Comment by kodan2k** [comment]
Latest Kodi v18.9 fixed the problem. RIP SPMC. I will miss its much faster load times.
