### ISSUE TITLE
[ondemandkorea] Cannot open directory

### ISSUE THREAD

**Issue by kodan2k** [xbmc-korean-tv/addons#9]
Ondemandkorea seems to have changed something again. You can't browse anymore:

```
T:2244  NOTICE: [xbmcswift2] Request for "/genre/drama/" matches rule for function "genre_view"
T:2244   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('postName',)
                                            Traceback (most recent call last):
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.ondemandkorea\addon.py", line 93, in <module>
                                                plugin.run()
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\script.module.xbmcswift2\lib\xbmcswift2\plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.ondemandkorea\addon.py", line 50, in genre_view
                                                info = scraper.parseGenre(genre, koPage=koPage)
                                              File "C:\Users\admin\AppData\Roaming\Kodi\addons\plugin.video.ondemandkorea\resources\lib\ondemandkorea.py", line 68, in parseGenre
                                                items.append({'title':item['title'], 'url':root_url+item['postName'], 'thumbnail':item['img'], 'latest':item['latest']})
                                            KeyError: ('postName',)
                                            -->End of Python script error report<--
ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ondemandkorea/genre/drama/
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ondemandkorea/genre/drama/) failed
```

**Comment by HaeDalByul** [comment]
Second this.
I have the same issue.

**Comment by xornidian** [comment]
Same problem for me since two days ago

**Comment by kodan2k** [comment]
Thanks, accessing directories and opening files is possible again. Unfortunately only for the first page of a show. Will make a new issue for that.
